09.django/0.done/d0530_03/sproject/fboard/urls.py
from django.urls import include,path
from . import views

app_name='fboard'
urlpatterns = [
    # 리스트,검색
    path('<int:nowpage>/<str:category>/<str:searchword>/fList/',views.fList,name='fList'),
    path('<int:nowpage>/<str:category>/<str:searchword>/fWrite/',views.fWrite,name='fWrite'),
    path('<int:nowpage>/<str:category>/<str:searchword>/<str:f_no>/fView',views.fView,name='fView'),
    # 답글쓰기
    path('<int:nowpage>/<str:category>/<str:searchword>/<str:f_no>/fReply',views.fReply,name='fReply'),
    # 삭제
    path('<int:nowpage>/<str:category>/<str:searchword>/<str:f_no>/fDelete',views.fDelete,name='fDelete'),
    # 수정
    path('<int:nowpage>/<str:category>/<str:searchword>/<str:f_no>/fUpdate',views.fUpdate,name='fUpdate'),
    path('event/',views.event,name='event'),
    path('event_view/',views.event_view,name='event_view'),
    path('commList/',views.commList,name='commList'),
    path('commWrite/',views.commWrite,name='commWrite'),
    
]

09.django/0.done/d0530_03/sproject/home/urls.py
from django.urls import include,path
from . import views

# home설정
app_name=''
urlpatterns = [
    path('',views.index,name='index'),
]

09.django/0.done/d0530_03/sproject/member/urls.py
from django.urls import include,path
from . import views

app_name='member'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    
]

09.django/0.done/d0530_03/sproject/product/urls.py
from django.urls import include,path
from . import views

app_name='product'
urlpatterns = [
    path('pWrite/',views.pWrite,name='pWrite'),
    path('pIndex/',views.pIndex,name='pIndex'),
    
]

09.django/0.done/d0530_03/sproject/sproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('member/',include('member.urls')),
    path('fboard/',include('fboard.urls')),
    path('product/',include('product.urls')),
] 

# 파일 업로드시 url구성
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

09.django/0.done/d0530_03/sproject/fboard/models.py
from datetime import datetime
from django.db import models
from member.models import Member

class Fboard(models.Model):
    f_no = models.AutoField(primary_key=True)
    # primary key:Member객체, id 1개 컬럼으로 받는데, ForeignKey:Member객체
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING,null=True)
    # id = models.CharField(max_length=100)
    f_title = models.CharField(max_length=1000)
    f_content = models.TextField()
    f_group = models.IntegerField(default=0)
    f_step = models.IntegerField(default=0)
    f_indent = models.IntegerField(default=0)
    f_hit = models.IntegerField(default=1)
    f_createdate =models.DateTimeField(default=datetime.now(),blank=True)
    f_updatedate = models.DateTimeField(default=datetime.now(),blank=True)
    f_file = models.ImageField(blank=True)
    
    def __str__(self):
        return self.f_title



class Comment(models.Model):
    c_no = models.AutoField(primary_key=True)
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING,null=True)
    fboard = models.ForeignKey(Fboard,on_delete=models.CASCADE)
    c_pw =  models.CharField(max_length=100,blank=True)
    c_content = models.TextField()
    c_date = models.DateTimeField(default=datetime.now(),blank=True)

09.django/0.done/d0530_03/sproject/fboard/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from fboard.models import Fboard, Comment
from member.models import Member
from django.db.models import F,Q 
from django.core.paginator import Paginator


def event(request):
    return render(request,'event.html')

def event_view(request):
    f_no = request.GET.get('f_no')
    context={'f_no':f_no}
    return render(request,'event_view.html',context)

def commList(request):
    f_no = request.GET.get('f_no')
    qs = Comment.objects.filter(fboard=f_no).order_by('-c_no')
    clist = list(qs.values())
    return JsonResponse(clist,safe=False)



def commWrite(request):
    f_no = request.GET.get('f_no')
    pw = request.GET.get('pw')
    content = request.GET.get('content')
    id = request.session.get('session_id')
    
    member = Member.objects.get(id=id)
    fboard = Fboard.objects.get(f_no=f_no)
    # print(f_no, pw, content,id)
    qs = Comment(member=member,fboard=fboard,c_pw=pw,c_content=content)
    qs.save()
    
    c_no=qs.c_no
    c_date=qs.c_date
    
    context = {'c_no':c_no, 'c_content':content, 'c_pw':pw,'c_date':c_date}
    return JsonResponse(context)




# 게시판 수정 함수
def fUpdate(request,nowpage,category,searchword,f_no):
    if request.method == 'GET':
        qs = Fboard.objects.get(f_no=f_no)
        context = {'board':qs,'nowpage':nowpage,'category':category,'searchword':searchword}
        return render(request,'fUpdate.html',context)
    else:
        # 수정form에서 데이터 전달
        id = request.POST.get('id')
        title = request.POST.get('title')
        content = request.POST.get('content')
        file = request.FILES.get('file',None)
        print("file : ",file)
        # db에 수정저장
        qs = Fboard.objects.get(f_no=f_no)
        qs.f_title = title
        qs.f_content = content
        if file:  # file등록이 되었으면 저장함.
            qs.f_file = file
            print("qs.f_file ok")
        
           
        qs.save()
        return redirect('fboard:fList',nowpage,category,searchword)

# 게시판 삭제 함수
def fDelete(request,nowpage,category,searchword,f_no):
    qs = Fboard.objects.get(f_no=f_no)
    qs.delete()
    return redirect('fboard:fList',nowpage,category,searchword)

# 게시판 답글쓰기 함수
def fReply(request,nowpage,category,searchword,f_no):
    if request.method == 'GET':
        qs = Fboard.objects.get(f_no=f_no) 
        context={'board':qs,'nowpage':nowpage,'category':category,'searchword':searchword}
        return render(request,'fReply.html',context)
    else:
        # id = request.session.session_id
        id = request.POST.get('id')
        print("id:",id)
        member = Member.objects.get(id=id)
        # request 넘어온 데이터타입 : str타입
        group = int(request.POST.get('group'))
        step = int(request.POST.get('step'))
        indent = int(request.POST.get('indent'))
        
        title = request.POST.get('title')
        content = request.POST.get('content')
        file = request.FILES.get('file',None)
        # file = request.POST.get('file',None)
        
        # 부모group에서 부모보다 큰 step 1씩증가, gt보다 큰수
        # reboard = Fboard.objects.filter(f_group=group,f_step_gt=step)
        # # F참조객체: db에서 검색을 해서 가져올수 있음.
        # reboard.update(f_step=F('f_step')+1)
        
        # 부모group에서 부모보다 큰 step 1씩증가, gt보다 큰수
        # F참조객체: db에서 검색을 해서 가져올수 있음.
        Fboard.objects.filter(f_group=group,f_step__gt=step).update(f_step=F('f_step')+1)
        
        # step: 출력순서, indent: 들여쓰기
        qs=Fboard(member=member,f_title=title,f_content=content,f_group=group\
            ,f_step=step+1,f_indent=indent+1,f_file=file)
        qs.save() # f_no
        
        return redirect('fboard:fList',nowpage,category,searchword)
    

# 게시판 읽기 함수
def fView(request,nowpage,category,searchword,f_no):
    qs = Fboard.objects.get(f_no=f_no)
    # 게시판리스트- f_group역순정렬, f_step순차정렬
    # qs = Fboard.objects.order_by('-f_group','f_step')
    # 이전글
    try:
        # 답글로 게시글이 등록될때 찾을수 있는 이전글검색
        qs_prev = Fboard.objects.filter(f_group=qs.f_group,f_step__lt=qs.f_step).order_by('-f_group','f_step').last().f_no
    except:  
        # 순차적으로 게시글이 등록될대 찾을수 있는 이전글검색
        try:
            qs_prev = Fboard.objects.filter(f_group__gt=qs.f_group).order_by('-f_group','f_step').last().f_no
        except:
            # 마지막 게시글 선택시 에러 처리
            qs_prev = Fboard.objects.order_by('-f_group','f_step').first().f_no
    
    # 다음글
    try:
        # 답글로 게시글이 등록될때 찾을수 있는 다음글검색
        qs_next = Fboard.objects.filter(f_group=qs.f_group,f_step__gt=qs.f_step).order_by('-f_group','f_step').first().f_no
    except:  
        # 순차적으로 게시글이 등록될대 찾을수 있는 다음글검색
        try:
            qs_next = Fboard.objects.filter(f_group__lt=qs.f_group).order_by('-f_group','f_step').first().f_no
        except:
            # 처음 게시글 선택시 에러 처리
            qs_next = Fboard.objects.order_by('-f_group','f_step').last().f_no
    
            
    print("qs_prev : ",qs_prev)
    qs.f_hit += 1
    qs.save()
    qsPrev = Fboard.objects.get(f_no=qs_prev)
    qsNext = Fboard.objects.get(f_no=qs_next)
    # 이전글 게시글 검색
    context={'board':qs,'boardPrev':qsPrev,'boardNext':qsNext,'nowpage':nowpage,'category':category,'searchword':searchword}
    return render(request,'fView.html',context)

# 게시판 글쓰기 함수
def fWrite(request,nowpage,category,searchword):
    if request.method == 'GET':
        context={"nowpage":nowpage,'category':category,'searchword':searchword}
        return render(request,'fWrite.html',context)
    else:
        # form넘어온 데이터
        id = request.POST.get("id")
        member = Member.objects.get(id=id)
        title = request.POST.get("title")
        content = request.POST.get("content")
        file = request.FILES.get('file',None)
        # db 저장
        qs = Fboard(member=member,f_title=title,f_content=content,f_file=file)
        qs.save()
        qs.f_group = qs.f_no
        qs.save()
        return redirect('fboard:fList',nowpage,category,searchword)
        
        

# 게시판 리스트 함수
def fList(request,nowpage,category,searchword):
    # GET,POST 포함
    # all,title,content
    if request.method =='POST':
        category = request.POST.get('category')
        searchword = request.POST.get('searchword')
        print("POST category : ",category,searchword)
    
    print("main category : ",category,searchword)
    # category분류
    if category == 'first':  # GET으로 들어옴.
        qs = Fboard.objects.order_by('-f_group','f_step')
    elif category == 'title':
        qs = Fboard.objects.filter(f_title__contains=searchword)
    elif category == 'content':
        qs = Fboard.objects.filter(f_content__contains=searchword)
    else: # all
        # or 검색 : title or content
        qs = Fboard.objects.filter(Q(f_title__contains=searchword)|Q(f_content__contains=searchword))
        # and 검색 : title and content
        # qs = Fboard.objects.filter(f_title__contains=searchword,f_content__contains=searchword)    
    
    paginator = Paginator(qs,10)     # 1페이지 나타낼수 있는 게시글 수 설정.  
    fList = paginator.get_page(nowpage) # 요청한 페이지의 게시글 10개를 전달
    print("count : ",qs.count)
    context={'fList':fList,'count':qs.count,'nowpage':nowpage,'category':category,'searchword':searchword}
    return render(request,'fList.html',context)

09.django/0.done/d0530_03/sproject/fboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
</head>
<body>
  <header>
    <ul>
      {% if not request.session.session_id %}
      <li>회원가입</li><span>|</span>
      <li><a href="{% url 'member:login' %}">로그인</a></li><span>|</span>
      {% else %}
      <li>{{request.session.session_nickname}}님</li><span>|</span>
      <li><a class="a_color" href="{% url 'member:logout' %}">로그아웃</a></li><span>|</span>
      {% endif %}
      <li><a class="a_color" href="{% url 'fboard:fList' nowpage=1 category='first' searchword='first' %}">고객행복센터</a></li><span>|</span>
      <li><a class="a_color" href="{% url 'product:pWrite' %}">상품등록</a></li><span>|</span>
      <li><a class="a_color" href="/admin">admin</a></li>
    </ul>
  </header>
  <!-- 메뉴 시작 -->
  <nav>
    <a href="{% url 'index' %}"><div class="logo"></div></a>
    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>
  <!-- 메뉴 끝 -->
  <section>
    {% block content-block %}
    {% endblock content-block %} 
  </section>
  <!-- 하단 부분 시작 -->
  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/0.done/d0530_03/sproject/fboard/templates/fList.html
{% extends 'base.html' %}
{% load static %}
    {% block content-block  %}
    <head>
      <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
      <script>
        function writeBtn(){
          location.href="{% url 'fboard:fWrite' nowpage category searchword %}"
        }

        function searchBtn(){
          if($("#searchword").val().length<=1){
            alert('2글자 이상 입력하셔야 검색이 가능합니다.')
            $("#searchword").focus()
            return false
          }
          document.search.submit()
        }
      </script>
    </head>
    <h1 id="noticeH1">NOTICE : {{ count }}</h1>
    <div class="wrapper">
      <form action="{% url 'fboard:fList' nowpage=1 category=category searchword=searchword %}" id="search" name="search" method="post">
        {% csrf_token %}
        <select name="category" id="category">
          <option value="all">전체</option>
          <option value="title">제목</option>
          <option value="content">내용</option>
        </select>
        
        <div class="title">
          <input type="text" name="searchword" id="searchword" size="16">
        </div>
        <button type="button" onclick='searchBtn()'><i class="fas fa-search"></i></button>
      </form>
    </div>
    
    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
      {% comment %} <tr>
        <td><span class="table-notice">NOTICE</span></td>
        <td class="table-title">신종코로나바이러스 예방관련 운영 안내</td>
        <td>2020-02-28</td>
      </tr> {% endcomment %}
      {% if fList %}
      {% for board in fList %}
      <tr>
        <td>{{board.f_no}}</td>
        <td class="table-title">
          <a href="{% url 'fboard:fView' nowpage category searchword board.f_no %}">
            {% if board.f_indent > 0 %}
            {% comment %} board.f_indent 글자로 인식 {% endcomment %}
            {% comment %} "x"|공백제거후 board.f_indent 만큼 리스트 처리 {% endcomment %}
            {% for i in "x"|rjust:board.f_indent %}
            ▶
            {% endfor %}  
            {% endif %}
            {{board.f_title}}
            {% if board.f_file %}
            <img src="/static/images/dicon1.png">
            {% endif %}
          </a>
        </td>
        <td>{{board.member.name}}</td>
        <td>{{board.f_updatedate|date:'Y-m-d H:i'}}</td>
        <td>{{board.f_hit}}</td>
      </tr>
      {% endfor %}
      {% else %}
      <tr>
        <td colspan='5'>데이터가 없습니다.</td>
      </tr>
      {% endif %}
    </table>
    <!-- 페이징 처리 -->
    <!-- 이전페이지 처리 -->
    <ul class="page-num">
      {% if fList.has_previous %}
      <a href="{% url 'fboard:fList' nowpage=1 category=category searchword=searchword  %}"><li class="first"></li></a>
      <a href="{% url 'fboard:fList' nowpage=fList.previous_page_number category=category searchword=searchword %}"><li class="prev"></li></a>
      {%else%}
      <li class="first"></li>
      <li class="prev"></li>
      {%endif%}
      <!-- 페이지순서 처리 -->
      {% for page in fList.paginator.page_range %}
      {% if page != nowpage %}
      <a href="{% url 'fboard:fList' nowpage=page category=category searchword=searchword  %}">
        <li class="num"><div>{{page}}</div></li>
      </a>
      {% else %}
      <li class="num on"><div>{{page}}</div></li>
      {% endif %}
      {% endfor %}  
      
      <!-- 다음페이지 처리 -->
      {% if fList.has_next %}
      <a href="{% url 'fboard:fList' nowpage=fList.next_page_number category=category searchword=searchword %}"><li class="next"></li></a>
      <a href="{% url 'fboard:fList' nowpage=fList.paginator.num_pages category=category searchword=searchword %}"><li class="last"></li></a>
      {% else %}
      <li class="next"></li>
      <li class="last"></li>
      {% endif %}
      
    </ul>
    
    <div class="write" onclick="writeBtn()">쓰기</div>
    {% endblock content-block  %}
  

09.django/0.done/d0530_03/sproject/fboard/templates/fReply.html
{% extends 'base.html' %}
{% load static %}
    {% block content-block  %}
<head>
<link rel="stylesheet" href="{% static 'css/write.css' %}">
  <script>
    function cancelBtn(){
      if (confirm('답글을 취소하시겠습니까?')){
        location.href="{% url 'fboard:fList' nowpage category searchword  %}"
      }

    }
  </script>
</head>
    <h1>답글쓰기</h1>
    <hr>

    <form action="{% url 'fboard:fReply' nowpage category searchword board.f_no %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>분류</th>
          <td>
            <div class="category-wrapper">
              <select name="category" id="category">
                <option value="notice">공지</option>
                <option value="event">이벤트</option>
              </select>  
            </div>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title" value="[답글] {{board.f_title}}">
          </td>
        </tr>
        <tr>
          <th>아이디</th>
          <td>{{request.session.session_id}}</td>
          <input type='hidden' name='id' value="{{request.session.session_id}}">
          <input type='hidden' name='group' value="{{board.f_group}}">
          <input type='hidden' name='step' value="{{board.f_step}}">
          <input type='hidden' name='indent' value="{{board.f_indent}}">

        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" id="text" cols="50" rows="10">[답글]
-------------------------------------------------
{{board.f_content}}
            </textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">작성완료</button>
        <button type="button" onclick="cancelBtn()" class="cancel">취소</button>
      </div>
    </form>
    {% endblock content-block  %}
 

09.django/0.done/d0530_03/sproject/fboard/templates/fView.html
{% extends 'base.html' %}
{% load static %}
  {% block content-block %}
  <head>
    <link rel="stylesheet" href="{% static 'css/read.css' %}">
  </head>
  <script>
    function deleteBtn(){
      if(confirm("데이터를 삭제하시겠습니까?")){
        location.href="{% url 'fboard:fDelete' nowpage category searchword board.f_no %}"
      }else{
        return false
      }
    }
  </script>
    <h1>NOTICE</h1>
    <table>
      <tr>
        <th>{{board.f_title}}</th>
      </tr>
      <tr>
        <td>{{board.member.name}}</td>
      </tr>
      <tr>
        <td>{{board.f_updatedate|date:'Y-m-d H:i'}}</td>
      </tr>
      <tr>
        <td>{{board.f_content}}</td>
      </tr>
      <tr>
        <td>파일이름 |{{board.f_file}}</td>
      </tr>
      <tr>
        <td>
          {% if board.f_file %}
          <img src="{{board.f_file.url}}">
          {% else %}
          <h4>이미지 없음</h4>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td><strong>다음글</strong> <span class="separator">|</span><a href="{% url 'fboard:fView' nowpage category searchword boardPrev.f_no %}">{{boardPrev.f_title}}</a></td>
      </tr>
      <tr>
        <td><strong>이전글</strong> <span class="separator">|</span><a href="{% url 'fboard:fView' nowpage category searchword boardNext.f_no %}"> {{boardNext.f_title}}</a></td>
      </tr>
    </table>

    <a href="{% url 'fboard:fList' nowpage category searchword  %}"><div class="list">목록</div></a>
    <div class="list"><a href="{% url 'fboard:fReply' nowpage category searchword board.f_no %}">답글</a></div>
    <div class="list" onclick="deleteBtn()">삭제</div>
    <div class="list"><a href="{% url 'fboard:fUpdate' nowpage category searchword board.f_no %}">수정</a></div>
  {% endblock content-block %}

09.django/0.done/d0530_03/sproject/fboard/templates/fWrite.html
{% extends 'base.html' %}
{% load static %}
    {% block content-block  %}
<head>
<link rel="stylesheet" href="{% static 'css/write.css' %}">
  {% if not request.session.session_id %}
  <script>
    alert("로그인을 하셔야 글쓰기가 가능합니다.")
    location.href="{% url 'member:login' %}"
  </script>
  {%endif%}
  <script>
    function cancelBtn(){
      if (confirm('글쓰기를 취소하시겠습니까?')){
        location.href="{% url 'fboard:fList' nowpage category searchword %}"
      }
    }
  </script>
</head>
    <h1>글쓰기</h1>
    <hr>

    <form action="{% url 'fboard:fWrite' nowpage category searchword %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>분류</th>
          <td>
            <div class="category-wrapper">
              <select name="category" id="category">
                <option value="notice">공지</option>
                <option value="event">이벤트</option>
              </select>  
            </div>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title">
          </td>
        </tr>
        <tr>
          <th>아이디</th>
          <td>{{request.session.session_id}}</td>
          <input type='hidden' name='id' value="{{request.session.session_id}}">
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" id="text" cols="50" rows="10"></textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">작성완료</button>
        <button type="button" onclick="cancelBtn()" class="cancel">취소</button>
      </div>
    </form>
    {% endblock content-block  %}