09.django/0.done/d0526_ing/sproject/fboard/urls.py
from . import views
from django.urls import include, path

app_name='fboard'
urlpatterns = [

    path('<int:nowpage>/<str:cat>/<str:swd>/fList/',views.fList,name='fList'),
    path('<int:nowpage>/fWrite/',views.fWrite,name='fWrite'),
    path('<int:nowpage>/<str:f_no>/fView/',views.fView,name='fView'),
    path('<int:nowpage>/<str:f_no>/fReply/',views.fReply,name='fReply'),
    path('<int:nowpage>/<str:f_no>/fDelete/',views.fDelete,name='fDelete'),
    path('<int:nowpage>/<str:f_no>/fUpdate/',views.fUpdate,name='fUpdate'),

]

09.django/0.done/d0526_ing/sproject/home/urls.py
from . import views
from django.urls import include, path

app_name=''
urlpatterns = [

    path('',views.index,name='index'),

]

09.django/0.done/d0526_ing/sproject/member/urls.py
from . import views
from django.urls import include, path

app_name='member'
urlpatterns = [

    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),

]

09.django/0.done/d0526_ing/sproject/product/urls.py
from . import views
from django.urls import include, path

app_name='product'
urlpatterns = [
    path('pList/',views.pList,name='pList'),
    path('pWrite/',views.pWrite,name='pWrite'),
    path('pIndex/',views.pIndex,name='pIndex'),
    path('<str:p_no>/pView/',views.pView,name='pView'),
]

09.django/0.done/d0526_ing/sproject/sproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('member/',include('member.urls')),
    path('fboard/',include('fboard.urls')),
    path('product/',include('product.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

09.django/0.done/d0526_ing/sproject/product/models.py
from django.db import models


class Product(models.Model):
    
    p_no  = models.AutoField(primary_key=True)
    p_name = models.CharField(max_length=100)
    p_servings  = models.CharField(max_length=100)
    p_unitPrice = models.IntegerField(max_length=10, default=0)
    p_description = models.TextField()
    p_category =models.CharField(max_length=20,default='요리')
    p_manufacturer  = models.CharField(max_length=20,blank=True)
    p_unit  = models.IntegerField(max_length=20,default=100)
    p_fileName =models.ImageField(max_length=100,blank=True)
    

    def __str__(self):
        return self.p_name

09.django/0.done/d0526_ing/sproject/product/views.py
from django.shortcuts import redirect, render
from numpy import product
from product.models import Product
# Create your views here.

def pList(request):
    qs = Product.objects.all().order_by('-p_no')
    context = {'products':qs}
    return render(request,'pList.html',context)


def pIndex(request):
    qs = Product.objects.all()
    context = {'products':qs}
    return render(request,'pIndex.html',context)


def pView(request,p_no):
    qs = Product.objects.get(p_no=p_no)
    context = {'product':qs}
    return render(request,'pView.html',context)

def pWrite(request):
    if request.method == 'GET':
        return render(request, 'pWrite.html')
    else:
        
        
        name = request.POST.get('pName')
        serving = request.POST.get('pServing')
        price = request.POST.get('pPrice')
        content = request.POST.get('content')
        catego = request.POST.get('Pcategory')
        manuf = request.POST.get('pManu')
        punit = request.POST.get('pUnit')
        
        file=request.FILES.get('file',None)
       
  
    
        
        qs = Product(p_name=name,p_servings=serving,p_unitPrice=price,p_description=content,p_category=catego,p_manufacturer=manuf,p_unit=punit,p_fileName=file)
        qs.save()

        return redirect('product:pList')

09.django/0.done/d0526_ing/sproject/product/templates/pIndex.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
		<link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:300,400,500,700,900&display=swap" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style_main.css' %}">
	</head>
	<body>
	 	<header>
	 		<div id="nav_up">
	 			<ul>
					{% if not request.session.session_id %}
	 					<li>회원가입</li>
	 					<li><a href="{% url 'member:login' %}">로그인</a></li>
					{% else %}
						<li>{{ request.session.session_nickname }}님</li>
						<li><a href="{% url 'member:logout' %}">로그아웃</a></li>
					{% endif %}
	 				<li><a href={% url 'fboard:fList' %}>고객행복센터</a></li>
	 				<li><a href="{% url 'product:pList' %}">메뉴리스트</a></li>
	 				
	 				<li><a href="/admin">ADMIN</a></li>
	 			</ul>
	 		</div>
	 		<nav>
	 			<h1></h1>
	 			<ul>
	 				<li>COOKIT소개</li>
	 				<li>메뉴</li>
	 				<li>리뷰</li>
	 				<li>이벤트</li>
	 				<li>MY쿡킷</li>
	 			</ul>
	 			<ul>
	 				<li><a href="#"><span>장바구니</span></a></li>
	 				<li><a href="#"><span>메뉴찾기</span></a></li>
	 			</ul>
	 		
	 		</nav>
	 	</header>
	 	<section>
	 		<div id="top_img">
	 			<div>
	 				<a href="#">
		 				<span>NEW</span>
		 				<span>3/16 신메뉴 출시</span>
		 				<span>따끈한 소울푸드<br>황태콩나물 해장국</span>
			 			<span><span></span>3인분</span>
			 			<span><span></span>조리 15분</span>
	 				</a>
	 				<span>16,800원 <a href="#"></a></span>
	 				<div>
	 					<a href="#"></a>
			 			<span>1/5</span>
			 			<a href="#"></a>
	 				</div>
	 			</div>
	 		</div>
	 		<div id="recomend">
	 			<div>
	 				<div>
		 				<span>얼큰한맛 <a href="#">▼</a></span>
		 				<span>메뉴<br>추천드려요</span>
		 				<span><a href="#">로그인</a>하시면 고객님의 구매내역과<br> 맛취향에 따라 딱맞는 맛있는 메뉴를 추천드려요</span>
		 			</div>
		 			<div></div>
		 			<img alt="우거지탕" src="static/images/recomand_tang.png">
		 			<div>
		 				<a href="#">얼큰소고기우거지탕</a>
		 				<div>
			 				<span>18,800원</span>
			 				<span>/3인분<a href="#"></a></span>
		 				</div>
	 				</div>
	 			</div>
	 		</div>
	 		<a href="#" id="event_banner"></a>
	 		<div id="best">
	 			<h2>실시간 베스트</h2>
	 			<ul>
        {% if products %}
        {% for p in products %}
	 				<li>
	 					<a href="{% url 'product:pView' p.p_no %}">
		 					<img alt="{{ p.p_name }}" src="/media/{{ p.p_fileName }}">
		 					<span id="best_top">BEST<br>{{ p.p_no }}</span>
	 					</a>
	 					<a href="#">
		 					<span>{{ p.p_name }}</span>
		 					<span>
		 						{{ p.p_unitPrice }}원
		 						<span>/{{ p.p_servings }}</span>
		 					</span>
	 					</a>
	 					<a href="#"></a>
	 				  </li>
        {% endfor %}
	 			{% else %}
          <li> 상품정보가 없습니다. </li>	
        {% endif %}
	 			</ul>
	 		</div>
	 		<div id="review">
	 			<h2>생생한 리뷰</h2>
	 			<div>
	 				<span></span>
	 				<span>속초식 코다리찜</span>
	 				<span>
						재료가 워낙 좋으니 생선이라도 비린내 걱정
						<br>없이 맛있었어요.나가서 사먹는것보다
						<br>내 집에서 믿고먹는 맛집, 쿡킷입니다!
					</span>
					<span></span>
	 				<span>by.for********</span>
	 				<div>
	 					<a href="#"></a>
			 			<span>1/5</span>
			 			<a href="#"></a>
	 				</div>
	 			</div>
	 			<img alt="코다리찜1" src="static/images/review01.jpg">
	 			<img alt="코다리찜2" src="static/images/review02.png">
	 			<span></span>
	 		</div>
			<div id="menu">
				<div>
					<img alt="메뉴상단01" src="static/images/menu_top01.jpg">
					<h2>쿡킷 메뉴보기<br>
					Premium Mealkit</h2>
					<span>
					장보기, 재료손질, 레시피검색 <strong>번거로움 OUT!</strong><br>
					초간편함은 물론, 완벽한 맛 쿡킷이 다~ 했네
					</span>
					<ul>
						<li>
							<a href="#">
								<span>
									<img alt="황태콩나물해장국" src="static/images/menu01.png">
								</span>
								<span>황태콩나물해장국</span>
								<span>16,800원<span>/3인분</span></span>
								<span class="new_menu">NEW</span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="군산식 아귀찜" src="static/images/menu02.png">
								</span>
								<span>군산식 아귀찜</span>
								<span>29,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="해물짬뽕전골" src="static/images/menu03.png">
								</span>
								<span>해물짬뽕전골</span>
								<span>22,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="스키야키" src="static/images/menu04.png">
								</span>
								<span>스키야키</span>
								<span>24,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="우삼겹쌀국수" src="static/images/menu05.png">
								</span>
								<span>우삼겹쌀국수</span>
								<span>24,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="빠네크림파스타" src="static/images/menu06.png">
								</span>
								<span>빠네크림파스타</span>
								<span>20,800원<span>/2인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="감바스알아히요" src="static/images/menu07.png">
								</span>
								<span>감바스알아히요</span>
								<span>20,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="대만식 우육탕면" src="static/images/menu08.png">
								</span>
								<span>대만식 우육탕면</span>
								<span>23,800원<span>/2인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="얼큰소고기우거지탕" src="static/images/menu09.png">
								</span>
								<span>얼큰소고기우거지탕</span>
								<span>18,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="두툼 갈치조림" src="static/images/menu10.png">
								</span>
								<span>두툼 갈치조림</span>
								<span>17,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="부추가득 오리불고기" src="static/images/menu11.png">
								</span>
								<span>부추가득 오리불고기</span>
								<span>24,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="버섯소불고기" src="static/images/menu12.png">
								</span>
								<span>버섯소불고기</span>
								<span>23,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="속초식 코다리찜" src="static/images/menu13.png">
								</span>
								<span>속초식 코다리찜</span>
								<span>24,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="사천식 깐풍새우" src="static/images/menu14.png">
								</span>
								<span>사천식 깐풍새우</span>
								<span>25,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="애호박돼지고기짜글이" src="static/images/menu15.png">
								</span>
								<span>애호박돼지고기짜글이</span>
								<span>22,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="칠리&크림 반반새우" src="static/images/menu16.png">
								</span>
								<span>칠리&크림 반반새우</span>
								<span>26,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="쿵팟퐁커리" src="static/images/menu17.png">
								</span>
								<span>쿵팟퐁커리</span>
								<span>20,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="소고기두부전골" src="static/images/menu18.png">
								</span>
								<span>소고기두부전골</span>
								<span>24,800원<span>/3인분</span></span>
							</a>
							<a href="#"></a>
						</li>
						<li>
							<a href="#">
								<span>
									<img alt="부채살 찹스테이크" src="images/menu19.png">
								</span>
								<span>부채살 찹스테이크</span>
								<span>20,800원<span>/2인분</span></span>
							</a>
							<a href="#"></a>
						</li>
					</ul>
				</div>
				<div>
					<img alt="핫딜" src="static/images/menu_hotdeal.jpg">
					<h2>놓칠 수 없는 기회 <br>
					오픈 한정 핫딜</h2>
					<span>파격적인 가격으로<br>
					쿡킷을 경험할 수 있는 기회를 잡으세요.</span>
					<a href="#">
						<img alt="쿡킷소개" src="static/images/menu_cj_intro.jpg">
						<h2>프리미엄 밀키트<br>
						COOKIT을 소개합니다.</h2>
						<span>COOKIT은 장보기, 재료손질, 계량 등 복잡한 과정 없이도<br>
						누구나 간편하게 특별한 집밥을 만들 수 있도록 도와드립니다.</span>
					</a>
				</div>
			</div>
			<div id="main_notice">
				<a href="#">
					<dl>
						<dt>공지사항</dt>
						<dd>미리보는 쿡킷 전체 메뉴 (3月)</dd>
					</dl>
				</a>
			</div>	 		
	 	</section>
		<footer>
			 	<div>
			 		<div>
				 		<a href="#"></a>
				 		<span>© COOKIT ALL RIGHTS RESERVED</span>
			 		</div>
			 		<div>
			 			<ul>
				 			<li>이용약관</li>
				 			<li class="foot_li">개인정보처리 방침</li>
				 			<li>법적고지</li>
				 			<li class="foot_end">사업자정보 확인</li>
			 			</ul>
			 			<div>
				 			<p>씨제이제일제당(주)대표이사 : 손경식,강신호,신현재 ㅣ 사업자등록번호 : 104-86-09535</p> 
				 			<p>주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560 ㅣ 통신판매업신고 중구 제 07767호 ㅣ 개인정보보호책임자 : 조영민</p>
							<p>이메일 : cjon@cj.net ㅣ 호스팅제공자 : CJ올리브네트웍스㈜</p> 
							<p>고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <a href="#">가입 사실 확인</a></p>
						</div>
			 		</div>
			 		<div>
			 		<span>CJ그룹계열사 바로가기 ▽</span>
			 		<span>고객행복센터 1668-1920</span>
			 		<a href="#">1:1 문의</a>
			 		</div>
			 	</div>
		</footer>
	</body>
</html>

09.django/0.done/d0526_ing/sproject/product/templates/pList.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">

  <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script>
    function writeBtn(){
      location.href = "{% url 'product:pWrite' %}"
    }
    function indexBtn(){
      location.href = "{% url 'index' %}"
    }
  </script>
</head>
<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li>고객행복센터</li> <span>|</span>
      <li>배송지역검색</li> <span>|</span>
      <li><a href="/admin">ADMIN</a></li>
    </ul>
  </header>

  <nav>
    <a href="{% url 'index' %}"><div class="logo"></div></a>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>NOTICE</h1>
    <div class="wrapper">
      <form action="/search" name="search" method="post">
        <select name="category" id="category">
          <option value="0">전체</option>
          <option value="title">제목</option>
          <option value="content">내용</option>
        </select>

        <div class="title">
          <input type="text" size="16">
        </div>
  
        <button type="submit"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <tr>
        <th>No.</th>
        <th>상품명</th>
        <th>가격</th>
        <th>카테고리</th>
        <th>재고</th>
      </tr>
      {% comment %} <tr>
        <td><span class="table-notice">NOTICE</span></td>
        <td class="table-title">신종코로나바이러스 예방관련 운영 안내</td>
        <td>2020-02-28</td>
      </tr> {% endcomment %}
      {% if products %}
        {% for p in products %}
        <tr>
          <td>{{ p.p_no }}</td>
          <td>
            {% if p.p_fileName %}
            <img src="/static/images/imgicon.png">
            {% endif %}
          <a href="{% url 'product:pView' p.p_no %}">{{ p.p_name }} </a> 
          </td>
          <td> <span>{{ p.p_unitPrice }}원 <span>/{{ p.p_servings }}</span></td>
          <td>{{ p.p_category }}</td>
          <td>{{ p.p_unit  }}</td>

        </tr>
        {% endfor %}
      {% else %}
      <tr>
        <td colspan='5'>데이터가 없습니다. </td>
      </tr>
      {% endif %}
    </table>

    <ul class="page-num">
      <li class="first"></li>
      <li class="prev"></li>
      <li class="num">
        <div>1</div>
      </li>
      <li class="next"></li>
      <li class="last"></li>
    </ul>

    <div class="write" onclick='writeBtn()'>쓰기</div>
    <div class="write" onclick='indexBtn()'>메뉴메인으로</div>
  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/0.done/d0526_ing/sproject/product/templates/pWrite.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pages - Login</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">

  <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script>
    function cancelBtn(){
      
      if (confirm('글쓰기를 취소하시겠습니까 ? ')){
        
        location.href= "{% url 'product:pList' %}"

      }
    }

  </script>

</head>

<body>
  <header>
    <ul>
      <li>회원가입</li> <span>|</span>
      <li>로그인</li> <span>|</span>
      <li><a href={% url 'fboard:fList' %}>고객행복센터</a></li>
      <li><a href="{% url 'product:pList' %}">메뉴</a></li>
      <li><a href="{% url 'product:pWrite' %}">메뉴추가</a></li>
      <li><a href="/admin">ADMIN</a></li>
    </ul>
  </header>

  <nav>
    <div class="logo"></div>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>

  <section>
    <h1>관리자 글쓰기</h1>
    <hr>

    <form action="{% url 'product:pWrite' %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>제품명</th>
          <td>
            <input type="text" name="pName" id="pName">
          </td>
        </tr>
        <tr>
          <th>Serving</th>
          <td>
          <select name="pServing"> 
              <option value='1인분'>1인분</option>
              <option value='2인분'>2인분</option>
              <option value='3인분'>3인분</option>
              <option value='4인분'>4인분</option>
          </select>
          </td>
        </tr>
        <tr>
          <th>가격</th>
          <td>
            <input type="text" name="pPrice" id="pPrice">
          </td>
        </tr>
        <tr>
          <th>설명</th>
          <td>
            <textarea name="content" cols="50" rows="10" id="content"></textarea>
          </td>
        </tr>
        <tr>
          <th>카테고리</th>
          <td>
            <select name="Pcategory"> 
              <option value='요리'>요리</option>
              <option value='찌개'>찌개</option>
            </select>
          </td>
        </tr>
        <tr>
          <th>제조사</th>
          <td>
            <input type="text" name="pManu" id="pManu">
          </td>
        </tr>
        <tr>
          <th>재고</th>
          <td>
            <input type="text" name="pUnit" id="pUnit">
          </td>
        </tr>     
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">작성완료</button>
        <button type="button" class="cancel" onclick='cancelBtn()'>취소</button>
      </div>
    </form>

  </section>

  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>