09.django/0.done/d0526_ing/sproject/fboard/urls.py
from . import views
from django.urls import include, path

app_name='fboard'
urlpatterns = [

    path('<int:nowpage>/<str:cat>/<str:swd>/fList/',views.fList,name='fList'),
    path('<int:nowpage>/fWrite/',views.fWrite,name='fWrite'),
    path('<int:nowpage>/<str:f_no>/fView/',views.fView,name='fView'),
    path('<int:nowpage>/<str:f_no>/fReply/',views.fReply,name='fReply'),
    path('<int:nowpage>/<str:f_no>/fDelete/',views.fDelete,name='fDelete'),
    path('<int:nowpage>/<str:f_no>/fUpdate/',views.fUpdate,name='fUpdate'),

]

09.django/0.done/d0526_ing/sproject/home/urls.py
from . import views
from django.urls import include, path

app_name=''
urlpatterns = [

    path('',views.index,name='index'),

]

09.django/0.done/d0526_ing/sproject/member/urls.py
from . import views
from django.urls import include, path

app_name='member'
urlpatterns = [

    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),

]

09.django/0.done/d0526_ing/sproject/product/urls.py
from . import views
from django.urls import include, path

app_name='product'
urlpatterns = [
    path('pList/',views.pList,name='pList'),
    path('pWrite/',views.pWrite,name='pWrite'),
    path('pIndex/',views.pIndex,name='pIndex'),
    path('<str:p_no>/pView/',views.pView,name='pView'),
]

09.django/0.done/d0526_ing/sproject/sproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('member/',include('member.urls')),
    path('fboard/',include('fboard.urls')),
    path('product/',include('product.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

09.django/0.done/d0526_ing/sproject/fboard/models.py
from operator import mod
from django.db import models
from datetime import datetime
from member.models import Member

class Fboard(models.Model):
    f_no = models.AutoField(primary_key=True)
    # primary key : Member객체, id 1개 컬럼으로 받는데, foreginkey: member객체
    member = models.ForeignKey(Member, on_delete=models.DO_NOTHING, null=True)
    # id = models.CharField(max_length=100)
    f_title = models.CharField(max_length=1000)
    f_content = models.TextField()
    f_group = models.IntegerField(default=0)
    f_step = models.IntegerField(default=0)
    f_indent = models.IntegerField(default=0)
    f_hit = models.IntegerField(default=1)
    f_createdate = models.DateTimeField(default=datetime.now(),blank=True)
    f_upedatedate = models.DateTimeField(default=datetime.now(),blank=True)
    f_file = models.ImageField(blank=True)
    
    def __str__(self):
        return self.f_title

09.django/0.done/d0526_ing/sproject/fboard/views.py
from django.shortcuts import redirect, render
from fboard.models import Fboard
from member.models import Member
from django.db.models import F 
from django.core.paginator import Paginator



# 게시판 리스트 함수 
def fList(request,nowpage,cat,swd):
    
    if request.method=='GET':
        qs = Fboard.objects.all().order_by('-f_group','f_step')
        # page = int(request.GET.get('nowpage',1))
        paginator = Paginator(qs,10) 
        fList = paginator.get_page(nowpage)
        context = {'fList':fList,'nowpage':nowpage}
        return render(request,'fList.html',context)
    else:
        qs = Fboard.objects.all().order_by('-f_group','f_step')
        # page = int(request.GET.get('nowpage',1))
        paginator = Paginator(qs,10) 
        fList = paginator.get_page(nowpage)
        cat = request.POST.get('category')
        swd = request.POST.get('searchword')
        context = {'fList':fList,'nowpage':nowpage}
        print(cat,swd)
        return render(request,'fList.html',context)

       

def fWrite(request,nowpage):
    if request.method == 'GET':
        context={'nowpage':nowpage}
        return render(request,'fWrite.html',context)
    else:
        id = request.POST.get('id')
        member = Member.objects.get(id=id)
        title = request.POST.get('title')
        content = request.POST.get('content')
        # file = request.POST.get('file',None)
        file=request.FILES.get('file',None)
        
        
        qs = Fboard(member=member,f_title=title,f_content=content,f_file=file)
        qs.save()
        qs.f_group=qs.f_no
        qs.save()
        return redirect('fboard:fList',nowpage)

def fView_old(request,nowpage,f_no):
    qs = Fboard.objects.get(f_no=f_no)
    qs.f_hit += 1
    qs.save()
    context = {'board':qs,'nowpage':nowpage}
    return render(request,'fView.html',context)

def fView(request,nowpage,f_no):
    qs = Fboard.objects.get(f_no=f_no)
    # 게시판리스트- f_group역순정렬, f_step순차정렬
    # qs = Fboard.objects.order_by('-f_group','f_step')
    # 이전글
    try:
        # 답글로 게시글이 등록될때 찾을수 있는 이전글검색
        qs_prev = Fboard.objects.filter(f_group=qs.f_group,f_step__lt=qs.f_step).order_by('-f_group','f_step').last().f_no
    except:  
        # 순차적으로 게시글이 등록될대 찾을수 있는 이전글검색
        try:
            qs_prev = Fboard.objects.filter(f_group__gt=qs.f_group).order_by('-f_group','f_step').last().f_no
        except:
            # 마지막 게시글 선택시 에러 처리
            qs_prev = Fboard.objects.order_by('-f_group','f_step').first().f_no
    
    # 다음글
    try:
        # 답글로 게시글이 등록될때 찾을수 있는 다음글검색
        qs_next = Fboard.objects.filter(f_group=qs.f_group,f_step__gt=qs.f_step).order_by('-f_group','f_step').first().f_no
    except:  
        # 순차적으로 게시글이 등록될대 찾을수 있는 다음글검색
        try:
            qs_next = Fboard.objects.filter(f_group__lt=qs.f_group).order_by('-f_group','f_step').first().f_no
        except:
            # 처음 게시글 선택시 에러 처리
            qs_next = Fboard.objects.order_by('-f_group','f_step').last().f_no
    
            
    print("qs_prev : ",qs_prev)
    qs.f_hit += 1
    qs.save()
    qsPrev = Fboard.objects.get(f_no=qs_prev)
    qsNext = Fboard.objects.get(f_no=qs_next)
    # 이전글 게시글 검색
    context={'board':qs,'boardPrev':qsPrev,'boardNext':qsNext,'nowpage':nowpage}
    return render(request,'fView.html',context)






def fReply(request,nowpage,f_no):
    if request.method == 'GET':
        qs = Fboard.objects.get(f_no=f_no)
        context = {'board': qs,'nowpage':nowpage}
        return render(request,'fReply.html',context)
    else:
        id = request.POST.get('id')
        group = int(request.POST.get('group'))
        step = int(request.POST.get('step'))
        indent = int(request.POST.get('indent'))
        
        member = Member.objects.get(id=id)
        title = request.POST.get('title')
        content = request.POST.get('content')
        # file = request.POST.get('file',None)
        file=request.FILES.get('file',None)
        
        # reboard = Fboard.objects.filter(f_group=group,f_step__gt=step)
        # reboard.update(f_step=F('f_step')+1)
        Fboard.objects.filter(f_group=group,f_step__gt=step).update(f_step=F('f_step')+1)
        qs = Fboard(member=member,f_title=title,f_content=content,f_group=group,f_step=step+1,f_indent=indent+1,f_file=file)
        
        qs.save()
        return redirect('fboard:fList',nowpage)

def fDelete(request,nowpage,f_no):
    qs = Fboard.objects.get(f_no=f_no)
    qs.delete()
    return redirect('fboard:fList',nowpage)


def fUpdate(request,nowpage,f_no):
    if request.method == 'GET':
        qs = Fboard.objects.get(f_no=f_no)
        context = {'board':qs,'nowpage':nowpage}
        return render(request,'fUpdate.html',context)
    else:        
        qs = Fboard.objects.get(f_no=f_no)

        qs.f_title = request.POST.get('title')
        qs.f_content = request.POST.get('content')
        file = request.POST.get('file',None) 

        if file:
            qs.f_file=file
        else:
            qs.f_file = request.FILES.get('file',None) 
        
        qs.save()     
        return redirect('fboard:fList',nowpage)

09.django/0.done/d0526_ing/sproject/fboard/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script>
    function writeBtn(){
      location.href = "{% url 'fboard:fWrite' nowpage %}"
    }

    function cancelBtn(){
      
      if (confirm('글쓰기를 취소하시겠습니까 ? ')){
        
        location.href= "{% url 'fboard:fList' nowpage %}"

      }
    }



    
  </script>
</head>
<body>
  <header>
    <ul>
      {% if not request.session.session_id %}
         <li>회원가입</li>
         <li><a href="{% url 'member:login' %}" class='a_color'>로그인</a></li>
      {% else %}
        <li>{{ request.session.session_nickname }}님</li>
        <li><a href="{% url 'member:logout' %}"  class='a_color' >로그아웃</a></li>
      {% endif %}
       <li><a href={% url 'fboard:fList' nowpage=1 %}  class='a_color' >고객행복센터</a></li>
       <li><a href="{% url 'product:pList' %}"  class='a_color'>메뉴리스트</a></li>
       
       <li><a href="/admin"  class='a_color' >ADMIN</a></li>
     </ul>
  </header>

  <nav>
    <a href="{% url 'index' %}"><div class="logo"></div></a>

    <div id="search">
      <div class="search"></div><br>
      <span>메뉴찾기</span>
    </div>

    <div id="cart">
      <div class="cart"></div><br>
      <span>장바구니</span>
    </div>

    <div class="nav-menu">
      <ul>
        <li>COOKIT소개</li>
        <li>COOKIT 메뉴</li>
        <li>리뷰</li>
        <li>이벤트</li>
        <li>MY쿡킷</li>
      </ul>  
    </div>
  </nav>
  <section>
            {% block content-block %}
            {% endblock content-block %}
  </section>
  <footer>
    <div class="wrapper">
      <div class="footer-left">
        <div class="footer-logo"></div>
        <div class="copyright">© COOKIT ALL RIGHTS RESERVED</div>
      </div>
  
      <div class="footer-center">
        <ul class="footer-nav">
          <li class="first-list">이용약관</li>
          <li class="green">개인정보처리 방침</li>
          <li>법적고지</li>
          <li>사업자정보 확인</li>
        </ul>
  
        <ul class="footer-info">
          <li class="first-list">씨제이제일제당(주)</li>
          <li>대표이사 : 손경식,강신호,신현재</li>
          <li>사업자등록번호 : 104-86-09535</li>
          <li class="first-list">주소 : 서울 중구 동호로 330 CJ제일제당 센터 (우) 04560</li>
          <li>통신판매업신고 중구 제 07767호</li>
          <li class="first-list">개인정보보호책임자 : 조영민</li>
          <li>이메일 : cjon@cj.net</li>
          <li>호스팅제공자 : CJ올리브네트웍스㈜</li>
        </ul>
  
        <div id="check">고객님은 안전거래를 위해 현금등으로 결제시 LG U+ 전자 결제의 매매보호(에스크로) 서비스를 이용하실 수 있습니다. <span class="check">가입 사실 확인</span></div>
      </div>
  
      <div class="footer-right">
        <div id="shortcut">
          <span>CJ그룹계열사 바로가기</span>
          <div class="shortcut"></div>
        </div>
  
        <div class="call">고객행복센터 1668-1920</div>
        <div class="inquery">1:1 문의</div>
      </div>
  
    </div>
  </footer>
</body>
</html>

09.django/0.done/d0526_ing/sproject/fboard/templates/fList.html
{% extends 'base.html' %}
{% load static %}
{% block content-block %}

<link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
<script  src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>

  function writeBtn(){
    location.href = "{% url 'fboard:fWrite' nowpage %}"
  }
  function searchBtn(){    
    if ($('#searchword').val().length<=1){
      alert('두글자 이상 입력해주세요')
      $('#searchword').focus()
      return false
    }
    document.search.submit()
  }




</script>

<h1>NOTICE</h1>
<div class="wrapper">
  <form action="{% url 'fboard:fList' nowpage  %}" name="search" method="post" id='search'>
    {% csrf_token %}
    <select name="category" id="category">
      <option value="all">전체</option>
      <option value="title">제목</option>
      <option value="content">내용</option>
    </select>
    
    <div class="title">
      <input type="text" size="16" id='searchword' name='searchword'>
    </div>
    
    <button type="button" onclick="searchBtn()"><i class="fas fa-search"></i></button>
  </form>
</div>

<table>
  <colgroup>
    <col width="15%">
    <col width="40%">
    <col width="15%">
    <col width="15%">
    <col width="15%">
  </colgroup>
  <tr>
    <th>No.</th>
    <th>제목</th>
    <th>작성자</th>
    <th>작성일</th>
    <th>조회수</th>
  </tr>
  {% comment %} <tr>
    <td><span class="table-notice">NOTICE</span></td>
    <td class="table-title">신종코로나바이러스 예방관련 운영 안내</td>
    <td>2020-02-28</td>
  </tr> {% endcomment %}
  {% if fList %}
  {% for board in fList %}
  <tr>
    <td>{{ board.f_no }}</td>
    <td class="table-title">
      <a href="{% url 'fboard:fView' nowpage board.f_no %}"> 
        {% if board.f_indent > 0 %}
        {% for i in "x"|rjust:board.f_indent %}
        ▶
        {% endfor %}
        {% endif %}
        {{ board.f_title }} </a>
        {% if board.f_file %}
        <img src="/static/images/imgicon.png">
        {% endif %}
      </td>
      
      <td>{{ board.member.nickname }}</td>
      <td>{{ board.f_upedatedate |date:'Y-m-d H:i'}}</td>
      <td>{{ board.f_hit }}</td>
      
    </tr>
    {% endfor %}
    {% else %}
    <tr>
      <td colspan='5'>데이터가 없습니다. </td>
    </tr>
    {% endif %}
  </table>
  
  <ul class="page-num">
    {% if fList.has_previous %}
    <a href="{% url 'fboard:fList' nowpage=1 %}"><li class="first"></li></a>
    <a href="{% url 'fboard:fList' nowpage=fList.previous_page_number %}"><li class="prev"></li></a>
    {% else %}
    <li class="first"></li>
    <li class="prev"></li>
    {% endif %}
    
    {% for page in fList.paginator.page_range %}
    {% if not page == nowpage %}
    <a href="{% url 'fboard:fList' nowpage=page %}">
      <li class="num"><div>{{ page }}</div></li>
    </a>
    {% else %}
    <li class="num on"><div>{{page}}</div></li>
    {% endif %}
    {% endfor %}
    
    
    {% if fList.has_next %}
    <a href="{% url 'fboard:fList' nowpage=fList.next_page_number %}"><li class="next"></li></a>
    <a href="{% url 'fboard:fList' nowpage=fList.paginator.num_pages %}"><li class="last"></li></a>
    {% else %}
    <li class="next"></li>
    <li class="last"></li>
    {% endif %}
  </ul>
  
  <div class="write" onclick='writeBtn()'>쓰기</div>
  

  {% endblock content-block %}

09.django/0.done/d0526_ing/sproject/fboard/templates/fReply.html
{% extends 'base.html' %}
{% load static %}
{% block content-block %}

  <link rel="stylesheet" href="{% static 'css/write.css' %}">

  <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script>
    function cancelBtn(){
      
      if (confirm('답글을 취소하시겠습니까? ')){
        
        location.href= "{% url 'fboard:fList' nowpage %}"

      }
    }

  </script>


    <h1>답글 글쓰기</h1>
    <hr>

    <form action="{% url 'fboard:fReply' nowpage board.f_no %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>분류</th>
          <td>
            <div class="category-wrapper">
              <select name="category" id="category">
                <option value="notice">공지</option>
                <option value="event">이벤트</option>
              </select>  
            </div>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title" value="[답글] {{ board.f_title }}">
          </td>
        </tr>
        
        <tr>
          <th>닉네임</th>
          <td>
            {{ request.session.session_nickname }}
            <input type='hidden' name="id" value = {{ request.session.session_id }}>
            <input type='hidden' name="group" value = {{ board.f_group }}>
            <input type='hidden' name="step" value = {{ board.f_step }}>
            <input type='hidden' name="indent" value = {{ board.f_indent }}>
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" cols="50" rows="10" id="content">[답글]
--------------------------------------
{{ board.f_content }}
--------------------------------------
          </textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">작성완료</button>
        <button type="button" class="cancel" onclick='cancelBtn()'>취소</button>
      </div>
    </form>

    
    {% endblock content-block %}

09.django/0.done/d0526_ing/sproject/fboard/templates/fUpdate.html
{% extends 'base.html' %}
{% load static %}
{% block content-block %}

  <link rel="stylesheet" href="{% static 'css/write.css' %}">

  <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script>
    function cancelBtn(){
      
      if (confirm('수정을 취소하시겠습니까? ')){
        
        location.href= "{% url 'fboard:fList' nowpage %}"

      }
    }

  </script>

    <h1>수정하기</h1>
    <hr>

    <form action="{% url 'fboard:fUpdate' nowpage board.f_no %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>분류</th>
          <td>
            <div class="category-wrapper">
              <select name="category" id="category">
                <option value="notice">공지</option>
                <option value="event">이벤트</option>
              </select>  
            </div>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title" value="{{ board.f_title }}">
          </td>
        </tr>
        
        <tr>
          <th>닉네임</th>
          <td>
            {{ request.session.session_nickname }}
            <input type='hidden' name="id" value = {{ request.session.session_id }}>
            <input type='hidden' name="group" value = {{ board.f_group }}>
            <input type='hidden' name="step" value = {{ board.f_step }}>
            <input type='hidden' name="indent" value = {{ board.f_indent }}>
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" cols="50" rows="10" id="content">{{ board.f_content }}
          </textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
        <tr>
          <th>이미지 이름 </th>
          <td>
          {% if board.f_file %}
            {{ board.f_file }}
            <input type ="hidden" name='refile' value="{{ board.f_file }}">
          {% else %}
          이미지 없음
          {% endif %}
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">수정완료</button>
        <button type="button" class="cancel" onclick='cancelBtn()'>취소</button>
      </div>
    </form>

     
    {% endblock content-block %}

09.django/0.done/d0526_ing/sproject/fboard/templates/fView.html
{% extends 'base.html' %}
{% load static %}
{% block content-block %}
<link rel="stylesheet" href="{% static 'css/read.css' %}">
<script  src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>

  function deleteBtn(){
    
    if(confirm("데이터를 삭제하시겠습니까? ")){
      location.href="{% url 'fboard:fDelete' nowpage board.f_no %}"
    }
  
    
  }
  
</script>

    <h1>NOTICE</h1>
      
    <table>
      <tr>
        <th>{{ board.f_title }}</th>
      </tr>
      <tr>
        <td>{{ board.member.name }}</td>
      </tr>
      <tr>
        <td>{{ board.f_upedatedate|date:'Y-m-d H:i' }}</td>
      </tr>
      <tr>
        <td class="article">
          {{ board.f_content }}
        </td>
      </tr>
      <tr>
        <td> 파일 이름 : {{ board.f_file }}</td>
      </tr>
      <tr>
        <td> 
          {% if board.f_file %}
           <img src=" {{ board.f_file.url }} "> 
          {% else %}
            이미지가 없습니다. 
          {% endif %}
        </td>
      </tr>
      <tr>
        <td><strong>다음글</strong> <span class="separator">|</span><a href="{% url 'fboard:fView' nowpage boardPrev.f_no %}">{{boardPrev.f_title}}</a></td>
      </tr>
      <tr>
        <td><strong>이전글</strong> <span class="separator">|</span><a href="{% url 'fboard:fView' nowpage boardNext.f_no %}"> {{boardNext.f_title}}</a></td>
      </tr>
    </table>

    <div class="list"><a href="{% url 'fboard:fList' nowpage %}">목록</a></div>
    <div class="list"><a href="{% url 'fboard:fReply' nowpage board.f_no %}">답글</a></div>
    <div class="list" onclick='deleteBtn()'>삭제</div>
    <div class="list"><a href="{% url 'fboard:fUpdate' nowpage board.f_no %}">수정</a></div>
    
    {% endblock content-block %}

09.django/0.done/d0526_ing/sproject/fboard/templates/fWrite.html
{% extends 'base.html' %}
{% load static %}
{% block content-block %}

<link rel="stylesheet" href="{% static 'css/write.css' %}">
<script  src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>
  function cancelBtn(){
    if (confirm('글쓰기를 취소하시겠습니까 ? ')){
      
      location.href= "{% url 'fboard:fList' nowpage %}"

    }
  } 
</script>



    <h1>관리자 글쓰기</h1>
    <hr>

    <form action="{% url 'fboard:fWrite' nowpage %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>분류</th>
          <td>
            <div class="category-wrapper">
              <select name="category" id="category">
                <option value="notice">공지</option>
                <option value="event">이벤트</option>
              </select>  
            </div>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" id="title">
          </td>
        </tr>
        
        <tr>
          <th>닉네임</th>
          <td>
            {{ request.session.session_nickname }}
            <input type='hidden' name="id" value = {{ request.session.session_id }}>
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" cols="50" rows="10" id="content"></textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="file" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">작성완료</button>
        <button type="button" class="cancel" onclick='cancelBtn()'>취소</button>
      </div>
    </form>

  
    {% endblock content-block %}